# KF-GINS configuration file

# Windows下使用KF-GINS时，文件路径中不能有中文
# When you run KF-GINS under Windows, there should be NO Chinese in the file path.

# IMU和GNSS数据文件路径
# imudata and gnssdata filepath
imupath: ""
gnsspath: ""

# 输出文件夹路径
# output folder path
outputpath: ""

# IMU文件列数 (只会用前7列IMU数据)
# IMU data columns, only use the first seven columns
imudatalen: 7
# IMU原始数据频率
# IMU datarate [Hz]
imudatarate: 200

# 处理时间段，结束时间设置为-1时则处理至IMU文件结束
# processing interval[s]
# process until the imufile end if set endtime to -1
starttime: 0
endtime: 0

# 初始状态
# initial state
# 初始位置, 纬度 经度 高程
# initial position, latitude, longitude, altitude. [deg, deg, m]
# TODO 给了一个大概的位置
initpos: [ 30.5, 114, 20 ]

# 初始速度, 北向速度, 东向速度, 垂向速度
# initial velocity, speed in the directions of north, east and down. [m/s, m/s, m/s]
initvel: [ 0.0, 0.0, 0.0 ]

# 初始姿态, 欧拉角(ZYX旋转顺序), 横滚, 俯仰, 航向
# initial attitude, euler angle(ZYX rotation), roll, pitch, yaw [deg, deg, deg]
initatt: [ 0.0, 0.0, 0.0 ]

# 初始IMU零偏和比例因子, IMU的三个轴(前、右、下)
# initial IMU bias and scale error, three axes of the imu (forward, right and down)
initgyrbias: [ 0, 0, 0 ]    # [deg/h]
initaccbias: [ 0, 0, 0 ]    # [mGal]
initgyrscale: [ 0, 0, 0 ]   # [ppm]
initaccscale: [ 0, 0, 0 ]   # [ppm]

# 初始状态标准差
# initial state std
# 初始位置标准差, 导航坐标系下 北向, 东向和垂向
# initial position std, north, east and down in n-frame. [m, m, m]
# TODO 经验估计或传感器供应商提供或实验测量
initposstd: [ 0.1, 0.1, 0.2 ]

# 初始速度标准差, 导航坐标系下北向、东向和垂向速度
# initial velocity std, north, east and down speed in n-frame. [m/s, m/s, m/s]
# TODO 同上
initvelstd: [ 0.05, 0.05, 0.05 ]

# 初始姿态标准差, 横滚、俯仰、航向角标准差
# initial attitude std, roll, pitch and yaw std. [deg, deg, deg]
# TODO 同上
initattstd: [ 0.5, 0.5, 1.0 ]

# 初始IMU零偏和比例因子标准差, IMU的三个轴
# initial IMU bias and scale error std, thrss axes of the imu
# 如果不指定，默认按照IMU零偏和比例因子误差参数设定
# default to the noise parameters of IMU bias and scale error.
#initbgstd: [ 50, 50, 50 ]          # [deg/h]
#initbastd: [ 250, 250, 250 ]       # [mGal]
#initsgstd: [ 1000, 1000, 1000 ]    # [ppm]
#initsastd: [ 1000, 1000, 1000 ]    # [ppm]

# IMU噪声建模参数, IMU的三个轴
# IMU noise parameters
imunoise:
  # (角随机游走 Angular Random Walk)： 
  arw: [0.24, 0.24, 0.24]          # [deg/sqrt(hr)]
  # vrw (速度随机游走 Velocity Random Walk)：
  vrw: [0.24, 0.24, 0.24]          # [m/s/sqrt(hr)]
  #  (陀螺仪偏差标准差 Gyro Bias Standard Deviation)：
  # [50.0, 50.0, 50.0] 表示陀螺仪零偏的标准差，单位为度/小时。
  # 陀螺仪偏差是指陀螺仪在没有旋转时输出的非零值。
  gbstd: [50.0, 50.0, 50.0]        # [deg/hr]
  # (加速度计偏差标准差 Accel Bias Standard Deviation)：
  # [250.0, 250.0, 250.0] 表示加速度计零偏的标准差，单位为mGal（1 mGal = 0.001 m/s²）。
  # 加速度计偏差是指加速度计在没有加速度时输出的非零值。
  abstd: [250.0, 250.0, 250.0]     # [mGal]
  # [1000.0, 1000.0, 1000.0] 表示陀螺仪比例因子的标准差，单位为ppm（百万分之一）。
  # 比例因子误差是指陀螺仪输出与实际旋转率之间的比例差异。
  gsstd: [1000.0, 1000.0, 1000.0]  # [ppm]
  # asstd (加速度计比例因子标准差 Accel Scale Factor Standard Deviation)：
  # [1000.0, 1000.0, 1000.0] 表示加速度计比例因子的标准差，单位为ppm。
  # 比例因子误差是指加速度计输出与实际加速度之间的比例差异。
  asstd: [1000.0, 1000.0, 1000.0]  # [ppm]
  corrtime: 1.0                    # [hr]

# 天线杆臂, IMU坐标系前右下方向
# antenna lever, forward, right and down in the imu frame. [m]
# antlever 参数通常指的是 GNSS 天线和 IMU 之间的距离。具体来说，这个参数定义了 GNSS 天线相对于 IMU 的位置偏移量。
antlever: [ 0.136, -0.301, -0.184 ]
